services:
  - type: web
    name: ege-russian-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: TELEGRAM_TOKEN
        sync: false
    plan: free
